<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="spido">


<!-- Import gazebo properties -->
<xacro:include filename="spido.gazebo" />


<!--<xacro:include filename="slope.urdf" />-->

<!--xacro:include filename="gps.urdf.xacro" -->
<!-- Model Properties  -->
<!-- Base Properties -->
  <xacro:property name="base_length" value="2.2" />
  <xacro:property name="base_width" value="1.1" />

  <!-- Wheel assembly Properties -->
  <xacro:property name="prismatic_length" value="0.3" />
  <xacro:property name="revolute_length" value="0.2" />
  <xacro:property name="wheel_radius" value="0.4" />

  <!-- joint placement -->
  <xacro:property name="center_to_prismatic_width" value="0.5" />
  <xacro:property name="center_to_prismatic_length" value="0.85" />
  <xacro:property name="center_to_prismatic_height" value="0.25" />

<!--                      Inertial properties                                -->
<xacro:macro name="default_inertial" params="mass">
    <inertial>
            <mass value="${mass}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                 iyy="1.0" iyz="0.0"
                 izz="1.0" />
    </inertial>
</xacro:macro>


<xacro:macro name="custom_inertial" params="mass ixx ixy ixz iyy iyz izz">
    <inertial>
            <mass value="${mass}" />
            <inertia ixx="${ixx}" ixy="${ixy}" ixz="${ixz}"
                 iyy="${iyy}" iyz="${iyz}"
                 izz="${izz}" />
    </inertial>
</xacro:macro>

  <!-- dummy link map -->

  <link name="spido_body"/>

  <joint name="spido_body_to_base_link" type="fixed"> <!-- -->
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="spido_body"/>
    <child link="base_link"/>
  </joint>


<!-- Robot model-->
  <link name="base_link">
    <visual>
      <geometry>
        <!-- <box size="${base_length} ${base_width} .5"/> -->
        <mesh filename="package://spido_description/meshes/spido.dae" scale="0.11 0.11 0.11"/>
      </geometry>
<!--1.5707963267948966-->
      <origin rpy="0 0 1.5707963267948966" xyz="0 0 0"/>
      <!-- <origin rpy="0 0 0" xyz="1.1 .55 .25"/> -->
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} .5"/>
      </geometry>
    </collision>
    <xacro:custom_inertial mass="800" ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="0.0"/>
  </link>

  <!-- wheel assembly macro -->
<xacro:macro name="wheel_assembly" params="prefix xyz rpy">
  <link name="${prefix}_prismatic">
    <visual>
      <geometry>
        <cylinder length="${prismatic_length}" radius="0.05"/>
      </geometry>
      <origin xyz="0 0 ${-prismatic_length/2}"/>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <xacro:default_inertial mass="10"/>
  </link>

<gazebo reference="${prefix}_prismatic">
  <material>Gazebo/Black</material>
</gazebo>

  <link name="${prefix}_revolute">
    <visual>
      <geometry>
         <cylinder length="${revolute_length}" radius="0.05"/>
      </geometry>
      <origin xyz="0 0 ${revolute_length/2}"/>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <xacro:default_inertial mass="10"/>
  </link>

  <link name="${prefix}_wheel">
    <visual>
      <geometry>
        <mesh filename="package://spido_description/meshes/simple_wheel.dae" scale="0.5 0.5 0.5"/>
        <!-- <cylinder length="0.1" radius="${wheel_radius}"/> -->
      </geometry>
      <origin rpy="0 1.5707963267948966 0" xyz="0 0 0"/>
      <!-- <origin xyz="0 0 0"/> -->
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.1" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="10"/>
  </link>

<gazebo reference="${prefix}_wheel">
  <!--<kp>100000000.0</kp> value for rubber -->
  <!--<kd>100.0</kd>  value for rubber -->
  <mu1>0.85</mu1> <!-- axial friction coefficient? -->
  <mu2>0.85</mu2> <!-- transversal friction coefficient? -->
  <!--<fdir1>1 0 0</fdir1>-->
  <!--<material>Gazebo/Wood</material>-->
</gazebo>

  <!-- Joints -->
  <joint name="base_link_to_${prefix}_prismatic" type="fixed"> <!-- type="prismatic" -->
    <parent link="base_link"/>
    <child link="${prefix}_prismatic"/>
    <!-- <limit effort="1000.0" lower="0.4" upper="0.4" velocity="0.5"/> --> <!-- upper -->
    <axis xyz="0 0 1"/>
    <origin rpy="${rpy}" xyz="${xyz}"/>
  </joint>

  <joint name="${prefix}_prismatic_to_${prefix}_revolute" type="revolute">
    <parent link="${prefix}_prismatic"/>
    <child link="${prefix}_revolute"/>
    <limit  lower="-0.3" upper="0.3" velocity="0.01" effort="1000000000.0"/> <!--  -->
    <axis xyz="-1 0 0"/>
    <origin rpy="-1.5707963267948966 1.5707963267948966 0" xyz="0 0 ${-prismatic_length}"/>
  </joint>

  <joint name="${prefix}_revolute_to_${prefix}_wheel" type="continuous"> <!-- type="revolute" -->
    <parent link="${prefix}_revolute"/>
    <child link="${prefix}_wheel"/>
    <limit effort="1000.0" velocity="30"/> <!-- lower="-3.141592653589793" upper="3.141592653589793" -->
    <axis xyz="0 0 1"/>
    <origin rpy="0 0 0" xyz="0 0 ${revolute_length}"/>
  </joint>


<transmission name="${prefix}_steering">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="${prefix}_prismatic_to_${prefix}_revolute">
<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
</joint>
  <actuator name="${prefix}_steering_motor">

    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>

<transmission name="${prefix}_wheel">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="${prefix}_revolute_to_${prefix}_wheel">
<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
</joint>
  <actuator name="${prefix}_wheel_motor">

    <mechanicalReduction>1</mechanicalReduction>
  </actuator>
</transmission>

</xacro:macro>


<xacro:wheel_assembly prefix="front_right" rpy="0 0 3.141592653589793" xyz="${center_to_prismatic_length} ${-center_to_prismatic_width} ${center_to_prismatic_height}"/>
<xacro:wheel_assembly prefix="front_left" rpy="0 0 0" xyz="${center_to_prismatic_length} ${center_to_prismatic_width} ${center_to_prismatic_height}"/>

<xacro:wheel_assembly prefix="rear_right" rpy="0 0 3.141592653589793" xyz="${-center_to_prismatic_length} ${-center_to_prismatic_width} ${center_to_prismatic_height}"/>
<xacro:wheel_assembly prefix="rear_left" rpy="0 0 0" xyz="${-center_to_prismatic_length} ${center_to_prismatic_width} ${center_to_prismatic_height}"/> -->




<!-- Hokuyo Laser >-->
 <!-- <link name="hokuyo_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>spi

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://spido_description/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="hokuyo_joint" type="fixed">
      <axis xyz="1 0 0" />
      <origin xyz="0 0 0.8" rpy="0 0 0"/> 
      <parent link="base_link"/>
      <child link="hokuyo_link"/>
  </joint>-->
  
  
  <!--<link name="slope_link">
  <inertial>
      <origin
        xyz="10 -6.06938101382426E-16 2.8821"
        rpy="0 0 0" />
      <mass
        value="18575000" />
      <inertia
        ixx="15548399405.3393"
        ixy="-9.69870109401819E-08"
        ixz="12794682.1006751"
        iyy="1470538291.32314"
        iyz="9.08893288334038E-07"
        izz="16880507047.6922" />
    </inertial>
    <visual>
      <origin
        xyz="-5 0 -1"
        rpy="-1.5707963267949 0 0" />
      <geometry>
        <mesh
          filename="package://spido_description/meshes/slope.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="-1.5707963267949 0 0" />
      <geometry>
        <mesh
          filename="package://spido_description/meshes/slope.STL" />
      </geometry>
    </collision>
  </link>-->
  

<!--<joint name="slope_joint" type="fixed">
      <axis xyz="1 0 0" />
      <origin xyz="0 0 -2" rpy="0 0 0"/> 
    <parent link="base_link" />
    <child link = "slope_link" />
</joint>-->
  
 <!-- <joint name="slope_joint" type="fixed">
      <axis xyz="1 0 0" />
      <origin xyz="0 0 -0.45" rpy="0 0 0"/> 
      <parent link="world"/>
      <child link="slope_link"/>
  </joint>-->
  
  
  


<!-- Hokuyo Laser >
  <link name="hokuyo_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>spi

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://spido_description/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="hokuyo_joint" type="fixed">
      <axis xyz="1 0 0" />
      <origin xyz="0 0 0.8" rpy="0 0 0"/> < xyz="0 ${base_width/2+0.3} 0" >
      <parent link="base_link"/>
      <child link="hokuyo_link"/>
  </joint>-->
  
<!-- Hokuyo Laser >-->

<xacro:arg name="gpu" default="false"/>
  <xacro:property name="gpu" value="$(arg gpu)" />


<xacro:include filename="$(find spido_description)/urdf/HDL-32E.urdf.xacro"/>
  <HDL-32E parent="base_link" name="velodyne2" topic="/velodyne_points" hz="10" samples="350" gpu="${gpu}">
    <origin xyz="0 0 0.8" rpy="0 0 0" />
  </HDL-32E>




</robot>
